version: "3.8"

services:

  selenium:
    image: "weaveworld/selenium:u20-20220901"  
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7900:7900
      - 5900:5900
      - 4444:4444
